// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab19CreateAPI.Models;

namespace lab19CreateAPI.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20181105035327_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab19CreateAPI.Models.ToDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDone");

                    b.Property<int?>("ListID");

                    b.Property<string>("Task");

                    b.HasKey("ID");

                    b.HasIndex("ListID");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("lab19CreateAPI.Models.ToDoList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("lab19CreateAPI.Models.ToDo", b =>
                {
                    b.HasOne("lab19CreateAPI.Models.ToDoList", "List")
                        .WithMany("ToDos")
                        .HasForeignKey("ListID");
                });
#pragma warning restore 612, 618
        }
    }
}
